spring:
    servlet:
        multipart:
            max-file-size: 512MB
            max-request-size: 512MB

    data:
        mongodb:
            database: ppc-sample
            host: localhost
            port: 27017

server:
    port : 7777


ppc:
    authCheckUrl: http://localhost:5999/api/v1/token/verify
    dirUpload : http://localhost:7777/api/v1/samples/
    corsOriginUrlClientAllowed: 'http://localhost:3000'

