spring:
    servlet:
        multipart:
            max-file-size: 512MB
            max-request-size: 512MB

server:
    port : 7777


ppc:
    authCheckUrl: http://localhost:5999/api/v1/token/verify